# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

hikes_list = [
  [ "Admiralty Point", 5, "Tri Cities", 1 ],
  [ "Al's Habrich Ridge Trail", 7, "Howe Sound", 2 ],
  [ "Aldergrove Regional Park", 5, "Surrey and Langley", 1 ],
  [ "Alice Lake", 6, "Howe Sound", 1 ],
  [ "Ancient Cedars Trail", 5, "Whistler", 2 ],
  [ "Baden Powell Deep Cove to Lynn Canyon", 12, "The North Shore", 2 ],
  [ "Baden Powell Lynn Canyon to Grouse", 10, "The North Shore", 2 ],
  [ "BCMC Trail", 3, "The North Shore", 3 ],
  [ "Big Cedar and Kennedy Falls Trail", 10,"The North Shore", 2 ],
  [ "Black Tusk", 29, "Whistler", 3 ],
  [ "Blackcomb Meadows", 8, "Whistler", 2 ],
  [ "Boundary Bay Regional Park", 5, "Tsawwassen and Delta", 1 ],
  [ "Brae Island Regional Park", 4.2, "Surrey and Langley", 1 ],
  [ "Brandywine Falls", 1, "Whistler", 1 ],
  [ "Brandywine Meadows", 6, "Whistler", 3 ],
  [ "Bridal Veil Falls", 0.8, "Fraser Valley East", 1 ],
  [ "Brohm Lake", 7.5, "Howe Sound", 2 ],
  [ "Brothers Creek Loop", 7, "The North Shore", 2 ],
  [ "Brunswick Point", 8, "Tsawwassen and Delta", 1 ],
  [ "Buntzen Lake", 8, "Tri Cities", 1 ],
  [ "Burnaby Lake", 10, "Vancouver City", 1 ],
  [ "Burnaby Mountain", 7.5, "Vancouver City", 1 ],
  [ "Burns Bog Delta Nature Reserve", 3, "Tsawwassen and Delta", 1 ],
  [ "Campbell Valley Regional Park", 4, "Surrey and Langley", 1 ],
  [ "Capilano Canyon", 2.6, "The North Shore", 1 ],
  [ "Capilano Pacific Trail", 15, "The North Shore", 1 ],
  [ "Cascade Falls", 0.75, "Fraser Valley East", 1 ],
  [ "Cheakamus Lake", 16, "Whistler", 1 ],
  [ "Cheam Lake Wetlands", 2.3, "Fraser Valley East", 1 ],
  [ "Conflict Lake", 12, "Whistler", 2 ],
  [ "Coquitlam Crunch", 4.5, "Tri Cities", 2 ],
  [ "Crown Mountain", 9.8, "The North Shore", 3 ],
  [ "Crystal Falls", 7, "Tri Cities", 1 ],
  [ "Cypress Falls", 3, "The North Shore", 1 ],
  [ "Dam Mountain", 5, "The North Shore", 1 ],
  [ "Deas Island Regional Park", 4.5, "Tsawwassen and Delta", 1 ],
  [ "Deer Lake", 5, "Vancouver City", 1 ],
  [ "Derby Reach Regional Park", 8, "Surrey and Langley", 1 ],
  [ "Dilly Dally Loop", 25, "Tri Cities", 3 ],
  [ "Dog Mountain", 5, "The North Shore", 1 ],
  [ "Eagle Bluffs", 8, "The North Shore", 2 ],
  [ "Elfin Lakes", 22, "Howe Sound", 2 ],
  [ "Elk Mountain", 7, "Fraser Valley East", 2 ],
  [ "Garibaldi Lake", 18, "Whistler", 2 ],
  [ "Goat Mountain", 8, "The North Shore", 2 ],
  [ "Gold Creek Falls", 5.5, "Ridge Meadows", 1 ],
  [ "Golden Ears", 24, "Ridge Meadows", 3 ],
  [ "Goldie Lake", 3, "The North Shore", 1 ],
  [ "Grouse Grind", 2.9, "The North Shore", 3 ],
  [ "Hanes Valley Trail", 16, "The North Shore", 3 ],
  [ "Harrison Grind", 7, "Fraser Valley East", 3 ],
  [ "Hayward Lake", 17, "Fraser Valley East", 1 ],
  [ "Hicks Lake", 6, "Fraser Valley East", 1 ],
  [ "High Falls Creek", 12, "Howe Sound", 2 ],
  [ "High Note Trail", 9.5, "Whistler", 2 ],
  [ "Hollyburn Mountain", 7, "The North Shore", 2 ],
  [ "Iona Beach Regional Park", 6, "Vancouver City", 1 ],
  [ "Joffre Lakes", 11, "Pemberton", 2 ],
  [ "Jug Island Beach", 5.5, "Tri Cities", 2 ],
  [ "Kanaka Creek Cliff Falls", 4, "Ridge Meadows", 1 ],
  [ "Kanaka Creek Riverfront", 2.5, "Ridge Meadows", 1 ],
  [ "Killarney Lake", 9, "Howe Sound", 1 ],
  [ "Levette Lake Loop", 11, "Howe Sound", 2 ],
  [ "Lighthouse Park", 6, "The North Shore", 1 ],
  [ "Lindeman Lake", 3.4, "Fraser Valley East", 2 ],
  [ "Lions Bay Loop", 4.5, "Howe Sound", 1 ],
  [ "Little Goat Mountain", 5.5, "The North Shore", 1 ],
  [ "Lost Lake Nature Trail", 5, "Whistler", 1 ],
  [ "Lower Hollyburn", 10, "The North Shore", 2 ],
  [ "Lynn Loop", 5.1, "The North Shore", 1 ],
  [ "Lynn Peak", 9, "The North Shore", 2 ],
  [ "Maplewood Flats", 2.5, "The North Shore", 1 ],
  [ "Mike Lake", 2, "Ridge Meadows", 1 ],
  [ "Minnekhada Regional Park", 10, "Tri Cities", 1 ],
  [ "Mount Cheam", 9.5, "Fraser Valley East", 2 ],
  [ "Mount Fromme", 10, "The North Shore", 2 ],
  [ "Mount Gardner", 17, "Howe Sound", 2 ],
  [ "Mount Seymour", 9, "The North Shore", 2 ],
  [ "Mount Strachan", 10.5, "The North Shore", 2 ],
  [ "Mount Thom", 10, "Fraser Valley East", 2 ],
  [ "Mundy Park", 6, "Tri Cities", 1 ],
  [ "Mystery Lake", 3, "The North Shore", 1 ],
  [ "Nairn Falls", 3, "Pemberton", 1 ],
  [ "Norvan Falls", 14, "The North Shore", 2 ],
  [ "Pacific Spirit Regional Park", 10, "Vancouver City", 1 ],
  [ "Panorama Ridge", 30, "Whistler", 3 ],
  [ "Petgill Lake", 11.5, "Howe Sound", 2 ],
  [ "Pitt Wildlife Loop", 15, "Ridge Meadows", 1 ],
  [ "Quarry Rock", 3.8, "The North Shore", 1 ],
  [ "Rainbow Lake", 16, "Whistler", 2 ],
  [ "Reifel Bird Sanctuary", 5, "Tsawwassen and Delta", 1 ],
  [ "Rice Lake", 3, "The North Shore", 1 ],
  [ "Rolley Lake", 5, "Fraser Valley East", 1 ],
  [ "Sasamat Lake", 8, "Tri Cities", 1 ],
  [ "Sendero Diez Vistas", 15, "Tri Cities", 2 ],
  [ "Serpentine Fen Nature Trail", 3.5, "Surrey and Langley", 1 ],
  [ "Shadow Lake", 5, "Pemberton", 1 ],
  [ "Shoreline Trail", 6, "Tri Cities", 1 ],
  [ "Skyline Trail", 5, "The North Shore", 2 ],
  [ "St Mark's Summit", 11, "The North Shore", 2 ],
  [ "Stanley Park", 6.5, "Vancouver City", 1 ],
  [ "Stawamus Chief", 11, "Howe Sound", 2 ],
  [ "Sumas Mountain", 13.5, "Fraser Valley East", 2 ],
  [ "Teapot Hill", 5, "Fraser Valley East", 1 ],
  [ "The Lions Binkert Trail", 16, "Howe Sound", 3 ],
  [ "Thunderbird Ridge", 6, "The North Shore", 1 ],
  [ "Two Canyon Loop", 8, "The North Shore", 2 ],
  [ "Tynehead Regional Park", 4.5, "Surrey and Langley", 1 ],
  [ "UBC Malcolm Knapp Research Forest", 8, "Ridge Meadows", 2 ],
  [ "Upper Shannon Falls", 7.5, "Howe Sound", 2 ],
  [ "Velodrome Trail", 3, "Vancouver City", 2 ],
  [ "Wedgemount Lake", 14, "Whistler", 3 ],
  [ "Whippoorwill Point Trail", 4, "Fraser Valley East", 1 ],
  [ "Whyte Lake", 5, "The North Shore", 1 ],
  [ "Whytecliff Park", 2, "The North Shore", 1 ],
  [ "Widgeon Falls", 6, "Ridge Meadows", 1 ],
  [ "Woodland Walk Trail", 8, "Tri Cities", 1 ]
]

events_list = [
  [ "TGIF", "Admirality Point", Date.parse("2015-11-1")],
  [ "Apples", "Burnaby Lake", Date.parse("2015-12-1")],
  [ "Elephant", "Admirality Point", Date.parse("2015-1-1")],
  [ "Midterms are Over", "Cheam Lake Wetlands", Date.parse("2015-12-13")],
  [ "Catching Sunrise", "Elk Mountain", Date.parse("2015-1-23")],
  [ "3 Day Trek", "Burnaby Lake", Date.parse("2015-12-30")]
] 

hikes_list.each do |name, distance, region, difficulty|
  Hike.create( name: name, distance: distance, region: region, difficulty: difficulty)
end

events_list.each do |name, location, date|
  Event.create( name: name, location: location, date: date )
end
